import firebase from '@react-native-firebase/app';
import firestore from '@react-native-firebase/firestore';
import moment from 'moment'

import { OrderStatusEnum, OrderActionEnum, RouteStatusEnum, RouteActionEnum } from 'DWcmn/Global';
import { prjAlert } from 'DWcmn/PrjCmnFunctions'
import { dwdbfsCustGetByAuth } from 'DWcmn/dwdbfsCust'
import { dwdbfsDrvGetByAuth } from 'DWcmn/dwdbfsDrv'
import { dwdbfsComboShopGetByAuth } from 'DWcmn/dwdbfsShop'
import { PaymentMethodEnum } from 'DWcmn/Global';
import { strX } from 'DWcmn/I18n';

//20210808 changed Route get to use ... rather than field by field
//20250703 removed dwdbfsOrderUpdateAdjustments

// CUST
// id: document id .. autogenerated unique 'readable' id
// authId: the auth token that 'owns' us
// name: 
// email: 
// address: 
// location: 
// city: 
// phoneNumber: 
// altAddress:
// altLocation:

// DRIVER
// id: document id .. hand-picked unique code
// authId: the auth token that 'owns' us 
// nickname .. name used in customer visible data
// name:
// email: 
// phoneNumber:
// shopId: 

// SHOP
// id: 
// name:
// email:
// address:
// city: 
// phoneNumber: 
// location: shpData.location,
// boundary: {}
// 
//   surchargeExpress: %charge for express service (-1 == not available)
//   surchargeSameDay: %charge for same day service (-1 == not available)
//   routeAvailableOffset: route no longer available x minutes before start
//   hoursOfPickupRoutes: how many routes we offer for choice
//   hoursOfDeliveryRoutes:
//   minFreeDelivery: minimum order for free delivery 
//   deliveryCharge: delivery charge if < minimum
//   allowCash:      allows one of COP or COD
//   allowCOD:       allows cash on delivery
//   allowCOP:       allows cash on pickup
//   allowOnline:    allows online payment
// 
// docId: shpDoc.id, //DEPRECATED

//   id:
//   custId:
//   shopId:
//   name:
//   routesArray:
//   routeTag:
//   status:
//   statusDate:
//   serviceLevel:
//   route:
//   transactions[]:
//   items[]:
//   lat: //DEPRECATED
//   long: //DEPRECATED
//   location: {lat,long}
//   address:
//   phoneNumber:
//   pickupRouteTime:
//   pickupRouteId:
//   pickupStop:
//   deliveryRouteTime:
//   deliveryRouteId:
//   deliveryStop:
//   isApproved:
//   totalPrice:
//   isPaid:
//   notes[]:
//   internal ......
//   docId:
//   selected:
//   distance: //UNUSED


export async function dwdbfsUserGetByAuthAndAppType(appType, authUid) {
   try {
      switch (appType) {
         case 'cst': return await dwdbfsCustGetByAuth(authUid)
         case 'drv': return await dwdbfsDrvGetByAuth(authUid)
         case 'shp': return await dwdbfsComboShopGetByAuth(authUid)
         default: return null
      }
   }
   catch (error) { prjAlert(error.message); }
}



export async function dwdbfsOrderGetById(orderId) {
   try {
      const orderDoc = await firestore().collection('Orders').doc(orderId).get();
      if (orderDoc.exists) {
         return dwdbfsOrderExtract(orderDoc.data())
      }
      else {
         return null
      }
   }
   catch (error) { prjAlert(error.message); }
}// end dwdbfsOrderGetById


//run a transaction to get the next sequential customer id
//by incrementing Counters.SHOP-xxxxx.lastAlloc
//throws error if problem
export async function dwdbfsOrderGenerateNewId(shopId) {
   let currId
   let divider
   const ctrDocRef = firestore().collection('ShopTop').doc(shopId.toString())
   await firestore().runTransaction(async trnx => {
      const shopDoc = await trnx.get(ctrDocRef)
      if (!shopDoc.exists) { throw "Unable to access Shop counters document" }
      if (!shopDoc.data().hasOwnProperty('lastAlloc')) { throw "Unable to access Shop Order Counter" }
      currId = shopDoc.data().lastAlloc + 1
      divider = shopDoc.data().divider
      await trnx.update(ctrDocRef, { lastAlloc: currId })
   })
   return shopId.toString() + "-" + divider + "-" + currId.toString().padStart(5, '0')
}// end dwdbfsOrderGenerateNewId

export function dwdbfsOrderLoadSnapshots(querySnapshot) {
   let localOrders = [];
   if (querySnapshot == null) { //take care of null just in case
      return localOrders;
   }
   querySnapshot.forEach((doc) => {
      let order = dwdbfsOrderExtract(doc.data())
      localOrders.push(order)
   })
   return localOrders;
} //end dwdbfsOrderLoadSnapshots

//extracts an order from an order document snapshot
export function dwdbfsOrderExtract(dbOrder) {
   let { status,
      paymentMethod,
      transactions,
      items,
      notes,
      pickupRouteTime,
      deliveryRouteTime,
      ...order } = dbOrder

   order.pickupRouteTime = dbOrder.pickupRouteTime ? dbOrder.pickupRouteTime.toDate() : null
   order.deliveryRouteTime = dbOrder.deliveryRouteTime ? dbOrder.deliveryRouteTime.toDate() : null
   order.status = OrderStatusEnum.enumValueOf(dbOrder.status)
   order.paymentMethod = PaymentMethodEnum.enumValueOf(dbOrder.paymentMethod)
   order.transactions = []
   order.items = []
   order.notes = []
   order.docId = dbOrder.id //TODO we really shouldn't need this field .. DEPRECATED
   order.selected = false
   order.distance = 0.0


   //extract the order items from database item  { code1:{category1:nnn,unitType1:nnn,etc}, 
   //                                              code2:{category2:nnn,unitType2:nnn,etc},
   //                                                  etc                          }
   Object.entries(dbOrder.items).forEach((dbItem) => {
      let item = {}
      item = dbItem[1]
      item.code = dbItem[0]
      item.key = dbItem[0] //20220320
      order.items.push(item)
   })


   dbOrder.transactions.forEach((dbTrans) => {
      let trans = {}
      trans.transDate = dbTrans.transDate.toDate()
      trans.status = dbTrans.status
      trans.prevStatus = dbTrans.prevStatus
      trans.strX = dbTrans.strX
      order.transactions.push(trans)
   })

   return order
} //end dwdbfsOrderExtract

export async function dwdbfsRouteAdd(shopId, schedDate, pickupExpress = false, pickupSameDay = false) {
   try {
      let newRouteRef
      newRouteRef = await firestore().collection("ShopTop").doc(shopId).collection("Routes").add(
         {
            shopId: shopId,
            // name: rteName, 
            schedDate: schedDate,
            status: 'pending',
            statusDate: null,
            pickupExpress: pickupExpress,
            pickupSameDay: pickupSameDay,
            orders: {},
            transactions: []
         })
      return (newRouteRef)
   }

   catch (error) {
      console.warn(error)
   }
}

//20250217 dwdbfsRouteLoadSingleSnapshot moved to dsdbfsRoute
// export function dwdbfsRouteLoadSingleSnapshot(docSnapshot) {

//    if (docSnapshot == null) { //take care of null just in case
//       return null;
//    }
//    let dbRoute = docSnapshot.data()
//    let { docId,
//       status,
//       schedDate,
//       ...localRoute } = dbRoute
//    localRoute.docId = docSnapshot.id
//    localRoute.status = RouteStatusEnum.enumValueOf(dbRoute.status)
//    localRoute.schedDate = dbRoute.schedDate.toDate()
//    localRoute.selected = false //TODO not sure we need this
//    return localRoute;
// } //end dwdbfsRouteLoadSingleSnapshot

export function dwdbfsRouteLoadSnapshots(querySnapshot) {

   try {
      let localRoutes = [];
      if (querySnapshot == null) { //take care of null just in case
         return localRoutes;
      }
      querySnapshot.forEach((doc) => {
         let dbRoute = doc.data()
         let { docId,
            status,
            schedDate,
            ...localRoute } = dbRoute
         localRoute.docId = doc.id
         localRoute.status = RouteStatusEnum.enumValueOf(dbRoute.status)
         localRoute.schedDate = dbRoute.schedDate.toDate()
         localRoute.selected = false //TODO not sure we need this
         localRoutes.push(localRoute)
         // localRoutes.push({
         //   name: dbRoute.name,
         //   status: RouteStatusEnum.enumValueOf(dbRoute.status),
         //   schedDate: dbRoute.schedDate.toDate(),
         //   // statusDate: dbRoute.statusDate,
         //   orders: dbRoute.orders,
         //   shopId: dbRoute.shopId,
         //   // openTime: dbRoute.openTime,
         //   driverId: dbRoute.driverId,
         //   docId: doc.id,
         //   selected: false
         // })
      })

      return localRoutes;

   }
   catch { (error => prjAlert(error.message)); }
} //end dwdbfsRouteLoadSnapshots

export async function dwdbfsOrderStatusAction(order, action) {
   switch (action) {
      case OrderActionEnum.view:
         break;
      case OrderActionEnum.approve: //this is done in another method
         break;
      case OrderActionEnum.addToRoute:
         break;
      case OrderActionEnum.removeFromRoute:
         break;
      case OrderActionEnum.accept:
         await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.inShop); break;
      case OrderActionEnum.cleaned:
         await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.readyForDelivery); break;
      case OrderActionEnum.noop:
         break;
      case OrderActionEnum.invalid:
         break;
      case OrderActionEnum.pickup:
         await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.pickedUp); break;
         break;
      case OrderActionEnum.failPickup:
         await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.missedPickup); break;
         break;
      case OrderActionEnum.undoPickup:
         await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.outForPickup); break;
         break;
      case OrderActionEnum.dropoff:
         await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.delivered); break;
         break;
      case OrderActionEnum.failDropoff:
         await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.missedDelivery); break;
         break;
      case OrderActionEnum.undoDropoff:
         await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.outForDelivery); break;
         break;

      case OrderActionEnum.cancel:
         await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.cancelled); break;
         break;
      case OrderActionEnum.confirm:
         await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.confirmed); break;
         break;
      case OrderActionEnum.pay:
         //TODO payment
         // await dwdbfsOrderUpdateStatus(order, OrderStatusEnum.); break;
         break;
   }

}//end dwdfsbOrderAction


//perform an action on the route
//NOTE that status is enum internally but string in DB
//for some status changes we record the time in the base fields
//in all cases we record the status change as a transaction
export async function dwdbfsRouteAction(route, orders, action) {
   const transTime = new Date();
   const currStatus = route.status.enumKey;
   var batch = firestore().batch()
   let newStatus = null
   switch (action) {
      case RouteActionEnum.lock:
         newStatus = RouteStatusEnum.locked
         break;
      case RouteActionEnum.unlock:
         newStatus = RouteStatusEnum.pending
         break;
      case RouteActionEnum.open: // change status of all orders appropriately
         // console.log('action open')
         newStatus = RouteStatusEnum.open
         orders.forEach((order) => {
            switch (order.status) {
               case OrderStatusEnum.assignedForPickup:
               case OrderStatusEnum.readyForPickup:
                  dwdbfsOrderUpdateStatusWithinBatch(batch, order.docId, order.status, OrderStatusEnum.outForPickup, transTime)
                  break;
               case OrderStatusEnum.assignedForDelivery:
               case OrderStatusEnum.readyForDelivery:
                  dwdbfsOrderUpdateStatusWithinBatch(batch, order.docId, order.status, OrderStatusEnum.outForDelivery, transTime)
                  break;
            }

         })

         break;
      case RouteActionEnum.close: //all pickups marked as atShop
         newStatus = RouteStatusEnum.completed//TODO what about ActionRequired?
         orders.forEach((order) => {
            switch (order.status) {
               case OrderStatusEnum.assignedForPickup:
               case OrderStatusEnum.readyForPickup:
               case OrderStatusEnum.outForPickup:
                  //TODO remove from from route?? because not picked up
                  break;
               case OrderStatusEnum.pickedUp:
                  dwdbfsOrderUpdateStatusWithinBatch(batch, order.docId, order.status, OrderStatusEnum.atShop, transTime)
                  break;
               default:
                  //TODO maybe everything has to be removed
                  break;
            }

         })

         break;
   } // end route action switch

   if (newStatus) {
      // console.log("route update", route.shopId, route.docId)
      const routeRef = firestore().collection("ShopTop").doc(route.shopId).collection('Routes').doc(route.docId)
      batch.update(routeRef, {
         status: newStatus.enumKey,
         statusDate: transTime,
         // transactions: firestore.FieldValue.arrayUnion({
         //   status: newStatus.enumKey,
         //   prevStatus: currStatus.enumKey,
         //   transDate: transTime
         // })
         transactions: firestore.FieldValue.arrayUnion({ xyz: '1234' })
      })
   }
   await batch.commit()
}//end dwdbfsRouteAction

export async function dwdbfsOrderDeliverWithCash(orderId) {
   const transTime = new Date();
   firestore().collection('Orders').doc(orderId).update({
      isPaid: true,
      status: OrderStatusEnum.delivered.enumKey,
      paymentDetails: { type: 'cash' },
      paymentMethod: PaymentMethodEnum.paidDelivery.enumKey,
      transTime: transTime,
      transactions: firestore.FieldValue.arrayUnion({
         transDate: transTime,
         strX: "trans.dropoffWithCash",
      })
   })
}//end dwdbfsOrderDeliverWithCash

export async function dwdbfsOrderPickupWithCash(orderId) {
   const transTime = new Date();
   await firestore().collection('Orders').doc(orderId).update({
      isPaid: true,
      status: OrderStatusEnum.pickedUp.enumKey,
      paymentDetails: { type: 'cash' },
      paymentMethod: PaymentMethodEnum.paidPickup.enumKey,
      transTime: transTime,
      transactions: firestore.FieldValue.arrayUnion({
         transDate: transTime,
         strX: "trans.pickupWithCash",
      })
   })
}//end dwdbfsOrderPickupWithCash

//TODO this sets payment method to initial ... not good
export async function dwdbfsOrderAcceptCash(order) {
   const currStatus = order.status
   const transTime = new Date();
   await firestore().collection('Orders').doc(order.docId).update({
      isPaid: true,
      paymentDetails: { type: 'cash' },
      paymentMethod: PaymentMethodEnum.paidCash.enumKey,
      transTime: transTime,
      transactions: firestore.FieldValue.arrayUnion({
         transDate: transTime,
         strX: "trans.cashReceived",
      })
   })
}//end dwdbfsOrderAcceptCash

export async function dwdbfsOrderPaidTemp(order) {
   const currStatus = order.status
   const transTime = new Date();
   await firestore().collection('Orders').doc(order.docId).update({
      isPaid: true,
      paymentDetails: { type: 'bank' },
      paymentMethod: PaymentMethodEnum.paidOnline.enumKey,
      transTime: transTime,
      transactions: firestore.FieldValue.arrayUnion({
         transDate: transTime,
         strX: "trans.onlinePayment",
      })
   })
}//end dwdbfsOrderPaidTemp

export async function dwdbfsOrderUpdateStatus(order, newStatus) {
   const currStatus = order.status
   const transTime = new Date();
   await firestore().collection('Orders').doc(order.docId).update({
      status: newStatus.enumKey,
      transTime: transTime,
      transactions: firestore.FieldValue.arrayUnion({
         status: newStatus.enumKey,
         prevStatus: currStatus.enumKey,
         transDate: transTime
      })
   })
}//end dwdbfsOrderUpdateStatus

function dwdbfsOrderUpdateStatusWithinBatch(batch, orderDocId, currStatus, newStatus, transTime) {
   const orderRef = firestore().collection('Orders').doc(orderDocId)
   batch.update(orderRef, {
      status: newStatus.enumKey,
      transTime: transTime,
      transactions: firestore.FieldValue.arrayUnion({
         transDate: transTime,
         status: newStatus.enumKey,
         prevStatus: currStatus.enumKey,
      })
   })
}//end dwdbfsOrderUpdateStatusWithinBatch

//NOTE .. this method update the item in the db...which was then read back
//BUT it is not that simple, there are many fields that can change when an item is priced.
//
//TODO need a way to indicate order pricing transaction .. for now omit
//TODO we may want to be able to have just weight and calculate the netPrice here
//  (but the net price should have been viewed and approved by shop so we shouldn't be redoing here)
//TODO should check for invalid status
//TODO CURRENTLY CALCULATE NETPRICE IN HERE .... NOT GOOD.
//TODO HAVE TO CALCULATE TOTAL PRICE OF ORDER
export async function dwdbfsOrderUpdateItemPricingOLD(order, index, type, amount) {
   const orderDoc = order.docId
   const items = order.items
   const item = items[index]
   if (item.isPriced) {
      //TODO this should be an error
   }
   else {
      let unpricedCount = -1 // we will be getting rid of one unpriced
      items.forEach((i) => { if (!i.isPriced) { ++unpricedCount } })

      let chg = {}
      const transTime = Date.now();
      //////////////////orderRec.transTime = transTime;
      switch (type) {
         case 'kg': item.weight = amount; item.netPrice = amount * item.unitPrice; break
         case 'pc': item.count = amount; item.netPrice = amount * item.unitPrice; break
         case 'spc': item.unitPrice = amount; item.netPrice = amount; break
      }
      item.isPriced = true

      let totalPrice = 0.0
      items.forEach((i) => { if (i.isPriced) { totalPrice += i.netPrice } })
      order.totalPrice = totalPrice
      //FOR NOW don't bother with pricing transaction
      // ??orderRec.status = newStatus;
      // const currStatus = orderRec.status.enumKey;
      // orderRec.transactions.push(
      //   realm.create('Transaction', { status: newStatus, prevStatus: currStatus, transDate: transTime })
      // );
      await firestore().collection('Orders').doc(order.docId).update({
         statusTime: transTime,
         totalPrice: order.totalPrice,
         ['items.' + item.code + '.count']: item.count,
         ['items.' + item.code + '.weight']: item.weight,
         ['items.' + item.code + '.netPrice']: item.netPrice,
         ['items.' + item.code + '.isPriced']: true,
      })
   }
}//end dwdbfsOrderUpdateItemPricing


//update the payment method ... no transaction is generated or status time change
//NOTE that payment method will also be changed by a pricing transaction (another method)
export async function dwdbfsOrderUpdatePaymentMethod(orderId, paymentMethod) {
   await firestore().collection('Orders').doc(orderId).update({
      paymentMethod: paymentMethod.enumKey,
   })

}//end dwdbfsOrderUpdatePaymentMethod

//TODO tidy up dwdbfsOrderAddNew
//returns the new document id
//will throw error for any error ... 
//  an order id may be allocated before the error.
//  the order creation and addition to routes occurs within a transaction
//NOTE that if we already have an order id from a QR code we use it
//20250213 use the order passed from QR if it is there
//20250525 mark the coupon as used if appropriate
//20251013 we no longer use QR code as order id .. it stays as separate field
export async function dwdbfsOrderAddNew(fauxOrder) {

   const orderId = await dwdbfsOrderGenerateNewId(fauxOrder.shopId)

   //prepare the list of items in itemsObj
   let itemsObj = {}
   for (const item of fauxOrder.items) {
      let { code, ...temp } = item
      // temp.isPriced = item.netPrice != 0
      itemsObj[item.code] = temp
   }

   await firestore().runTransaction(async trnx => {
      let newRef
      let transDate = new Date()
      //if we have a pickup route assigned original status is assignedForPickup ow readyForPickup
      let status = fauxOrder.pickupRouteTime ? OrderStatusEnum.assignedForPickup.enumKey
         : OrderStatusEnum.readyForPickup.enumKey
      let { routesArray, transactions, items, notes, ...obj } = fauxOrder
      obj.creationDate = transDate
      obj.archive = false
      obj.id = orderId
      obj.status = status
      obj.statusDate = transDate
      obj.route = null
      obj.transactions = []
      obj.items = itemsObj
      obj.isPaid = false
      obj.paymentMethod = PaymentMethodEnum.initial.enumKey
      obj.paymentDetails = {}
      obj.notes = []        // notes: [...dbOrder.notes],
      // obj.routesArray = [fauxOrder.pickupRouteTime, fauxOrder.deliveryRouteTime] //SCSC
      obj.routesArray = [fauxOrder.pickupRouteId, fauxOrder.deliveryRouteId]
      obj.transactions = firestore.FieldValue.arrayUnion({
         status: status,
         prevStatus: null,
         transDate: transDate
      })
      newRef = firestore().collection('Orders').doc(orderId.toString())
      trnx.set(newRef, obj)

      if (['applies','maybe'].includes (fauxOrder.couponStatus)){
      await trnx.update(firestore().collection("Coupons").doc(fauxOrder.coupon.docId), {'isUsed':true })

      }

      await trnx.update(firestore().collection("ShopTop").doc(fauxOrder.shopId).collection("Routes").doc(fauxOrder.pickupRouteId), { ['orders.' + newRef.id]: 'pickup' })
      await trnx.update(firestore().collection("ShopTop").doc(fauxOrder.shopId).collection("Routes").doc(fauxOrder.deliveryRouteId), { ['orders.' + newRef.id]: 'delivery' })

   })
   return orderId
}
