import firebase from '@react-native-firebase/app';
import firestore from '@react-native-firebase/firestore';
import moment from 'moment'

import { prjAlert } from 'DWcmn/PrjCmnFunctions'
import { cmnAlertPopup } from './cmnAnnunciationFunctions';
import { PaymentMethodEnum } from 'DWcmn/Global';
import { strX } from 'DWcmn/I18n';

//20230218 moved cust functions to this separate file
//20250714 changed the return of dwdbfsCustGet to return undefined not {} if not found

// CUST
// id: document id .. autogenerated unique 'readable' id
// altStop: (optional)
// authId: the auth token that 'owns' us
// authType: email, google, facebook, ios?
// email:
// homeStop:
// name: 
// phoneNumber:
// shopId:
// altAddress:
// altLocation:


//errors not caught and no indication if delete was successful
export async function dwdbfsCustDelete(custId) {
   //TODO check that there are no outstanding orders
   await firestore().collection('Customers').doc(custId).delete();
}// end dwdbfsGetCust

//returns the customber data or undefined
export async function dwdbfsCustGet(custId) {
   try {
      const custDoc = await firestore().collection('Customers').doc(custId).get();
      return custDoc.data()
   }
   catch (error) { prjAlert(error.message); }
}// end dwdbfsGetCust

export async function dwdbfsCustGetByAuth(authId) {
   let custData
   try {
      const querySnapshot = await firestore().collection('Customers').where('authId', "==", authId).limit(1).get();
      if (querySnapshot.empty) {
         return null
      }
      else {
         custData = querySnapshot.docs[0].data()
         //TODO remove this code after testing
         // custData.homeStop = {
         //   code:'home',
         //   address:custData.address,
         //   location:custData.location,
         //   instructions:'home instructions'
         // }
         // custData.altStop = {
         //   code:'alternate',
         //   address:custData.address,
         //   location:custData.location,
         //   instructions:'alternate instructions'
         // }
         return { ...custData } //TODO is this necessary?
      }
   }
   catch (error) { prjAlert(error.message); }
}// end dwdbfsCustGetByAuth

export async function dwdbfsCustGetByEmail(email) {
   let custData
   try {
      const querySnapshot = await firestore().collection('Customers').where('email', "==", email).limit(1).get();
      if (querySnapshot.empty) {
         return null
      }
      else {
         custData = querySnapshot.docs[0].data()
         //TODO remove this code after testing
         // custData.homeStop = {
         //   code:'home',
         //   address:custData.address,
         //   location:custData.location,
         //   instructions:'home instructions'
         // }
         // custData.altStop = {
         //   code:'alternate',
         //   address:custData.address,
         //   location:custData.location,
         //   instructions:'alternate instructions'
         // }
         return { ...custData } //TODO is this necessary?
      }
   }
   catch (error) { prjAlert(error.message); }
}// end dwdbfsCustGetByEmail

//write new customer and read it back, returns null if unsuccessful
//catches and annunciates any errors
export async function dwdbfsCustAdd(authId, data) {
   try {
      let currId = (await dwdbfsCustGenerateNewId()).toString()

      //create homeStop (containing address and instructions for the home address)
      // data.homeStop = {
      //    code: 'home',
      //    address: data.address,
      //    location: data.location,
      //    instructions: data.instructions
      // }
      // delete data.address
      // delete data.location
      // delete instructions

      //create altStop if there is alternate address(/location) data
      // data.altStop = data.altAddress ? {
      //    code: 'alternate',
      //    address: data.altAddress,
      //    location: data.altLocation,
      //    instructions: data.altInstructions
      // } : null
      // delete data.altAddress
      // delete data.altLocation
      // delete altInstructions

      await firestore().collection('Customers').doc(currId).set({
         id: currId.toString(),
         authId: authId,
         ...data
      })
      return dwdbfsCustGet(currId)
   }
   catch (err) {
      cmnAlertPopup({ title: 'ERROR adding customer', text: err.message })
      return null
   }

}

//run a transaction to get the next sequential customer id
//by incrementing Counters.CustId.lastAlloc
//throws error if problem
async function dwdbfsCustGenerateNewId() {
   let currId
   const ctrDocRef = firestore().collection('Counters').doc('CustId')
   await firestore().runTransaction(async trnx => {
      const counterDoc = await trnx.get(ctrDocRef)
      if (!counterDoc.exists) { throw "Unable to access Counters document" }
      if (!counterDoc.data().hasOwnProperty('lastAlloc')) { throw "Unable to access CustId Counter" }
      currId = counterDoc.data().lastAlloc + 1
      await trnx.update(ctrDocRef, { lastAlloc: currId })
   })
   return currId
}// end dwdbfsCustGenerateNewId

//returns true iff successful
//catches and annunciates any errors
export async function dwdbfsCustUpdate(cust) {
   try {
      await firestore().collection('Customers').doc(cust.id).update(cust)
      return true
   }
   catch (err) {
      cmnAlertPopup({ title: 'ERROR dwdbfsCustUpdateProfile', text: err.message })
      return false
   }

}//end dwdbfsCustUpdateProfile
//returns true iff successful
//catches and annunciates any errors
export async function dwdbfsCustUpdateProfile(currId, name, phoneNumber, email) {
   try {
      await firestore().collection('Customers').doc(currId).update({
         name: name,
         phoneNumber: phoneNumber,
         email: email
      })
      return true
   }
   catch (err) {
      cmnAlertPopup({ title: 'ERROR dwdbfsCustUpdateProfile', text: err.message })
      return false
   }
}//end dwdbfsCustUpdateProfile

//REMOVED ... doesn't work if you have to change fields inside an object
// //returns true iff successful
// //catches and annunciates any errors
// export async function dwdbfsCustUpdateFields(currId, fields) {
//    try {
//       await firestore().collection('Customers').doc(currId).update({
//          ...fields
//       })
//       return true
//    }
//    catch (err) {
//       cmnAlertPopup({ title: 'ERROR dwdbfsCustUpdateFields', text: err.message })
//       return false
//    }
// }//end dwdbfsCustUpdateFields

//returns true iff successful
//catches and annunciates any errors
export async function dwdbfsCustUpdateAddresses(currId, homeStop, altStop) {
   try {
      await firestore().collection('Customers').doc(currId).update({
         homeStop: homeStop,
         altStop: altStop
      })
      return true
   }
   catch (err) {
      cmnAlertPopup({ title: 'ERROR updating customer addresses', text: err.message })
      return false
   }
}//end dwdbfsCustUpdateHomeStop

//throws any errors
export async function dwdbfsCustUpdateHomeStop(currId, homeStop) {
   await firestore().collection('Customers').doc(currId).update({ homeStop: homeStop, })
}//end dwdbfsCustUpdateHomeStop

//throws any errors
export async function dwdbfsCustUpdateAltStop(currId, altStop) {
   await firestore().collection('Customers').doc(currId).update({ altStop: altStop })
}//end dwdbfsCustUpdateAltStop
