export function generatePriceList() {
    let priceList = {
  
      entries: [
        {
          key: "1", name: "Handwash and Fold",
          entries: [
            {
              code: "A001",
              name: "Shirt/T-Shirt/Polo-T/Blouse",
              unitPrice: 7,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "A002",
              name: "Trousers/Jeans/Shorts/Joggerpants",
              unitPrice: 7,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "A003",
              name: "Vest/Sweater",
              unitPrice: 7,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "A004",
              name: "Skirt (Short/Long)",
              unitPrice: 7,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "A005",
              name: "Dress (Short / Long)",
              unitPrice: 7,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "A007",
              name: "Coat/Blazer/Jacket",
              unitPrice: 10,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "A008",
              name: "Baju Kurung 2pcs (set)",
              unitPrice: 7,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "A009",
              name: "Jubah",
              unitPrice: 7,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "A010",
              name: "Saree",
              unitPrice: 8,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "A011",
              name: "Tudung/Scarf/Necktie",
              unitPrice: 3,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "A012",
              name: "Undergarment",
              unitPrice: 3,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
          ]
        },
          {
          key: "2", name: "Wash and Fold Bedding",
          entries: [
            {
              code: "B001",
              name: "Bedding",
              unitPrice: 6,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B002",
              name: "Comforter (S)",
              unitPrice: 15,
              unitType: "spc",
              procTimeReg: 48,
              procTimeExp: 12,
            },
            {
              code: "B003",
              name: "Comforter (M)",
              unitPrice: 20,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B004",
              name: "Comforter (K)",
              unitPrice: 24,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B005",
              name: "Duvet (S)",
              unitPrice: 15,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B006",
              name: "Duvet (M)",
              unitPrice: 20,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B007",
              name: "Duvet (K)",
              unitPrice: 24,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B008",
              name: "Mattress Protector (S)",
              unitPrice: 15,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B009",
              name: "Mattress Protector (M)",
              unitPrice: 20,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B010",
              name: "Mattress Protector (K)",
              unitPrice: 24,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B011",
              name: "Curtain",
              unitPrice: 6,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B012",
              name: "Cushion Cover/Sofa Cover",
              unitPrice: 6,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B013",
              name: "Tablecloth",
              unitPrice: 6,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "B014",
              name: "Carpet",
              unitPrice: 2,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
          ]
        },
        {
          key: "3", name: "Ironing (Clothes)",
          entries: [
            {
              code: "C001",
              name: "Shirt/T-Shirt/Polo-T/Blouse",
              unitPrice: 3,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C002",
              name: "Trousers/Jeans/Shorts/Joggerpants",
              unitPrice: 3,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C003",
              name: "Vest/Sweater",
              unitPrice: 5,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C004",
              name: "Skirt (Short/Long)",
              unitPrice: 5,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C005",
              name: "Coat/Dress (Short/Long)",
              unitPrice: 5,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C006",
              name: "Coat/Blazer/Jacket",
              unitPrice: 7,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C007",
              name: "Baju Kurung 2pcs (set)",
              unitPrice: 5,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C008",
              name: "Baju Melayu 2pcs (set)",
              unitPrice: 5,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C009",
              name: "Jubah",
              unitPrice: 5,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C010",
              name: "Punjabi Suit 2pcs (set)",
              unitPrice: 5,
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C011",
              name: "Saree",
              unitPrice: 7,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C012",
              name: "Undergarment",
              unitPrice: 2,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "C013",
              name: "Tudung/Scarf/Necktie",
              unitPrice: 2,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
          ]
        },
  
        {
          key: "4", name: "Ironing Bedding",
          entries: [
            {
              code: "D001",
              name: "Bedsheet/Duvet Cover",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D002",
              name: "Comforter (S)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D003",
              name: "Comforter (Q)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D004",
              name: "Comforter (K)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D005",
              name: "Duvet (S)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D006",
              name: "Duvet (Q)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D007",
              name: "Duvet (K)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D008",
              name: "Pillowcase / Bolstercase",
              unitPrice: 6,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D009",
              name: "Curtain Sheer (pc)",
              unitPrice: 20,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D010",
              name: "Cushion Cover",
              unitPrice: 18,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D011",
              name: "Sofa Cover",
              unitPrice: 18,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D012",
              name: "Tablecloth",
              unitPrice: 18,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D013",
              name: "Pillow",
              unitPrice: 25,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "D014",
              name: "Carpet",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
          ]
        },
  
        {
          key: "5", name: "Washing Ironing (Clothes)",
          entries: [
            {
              code: "E001",
              name: "Shirt/T-Shirt/Polo-T/Blouse",
              unitPrice: 5,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E002",
              name: "Trousers/Jeans/Shorts/Joggerpants",
              unitPrice: 5,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E003",
              name: "Vest/Sweater",
              unitPrice: 7,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E004",
              name: "Skirt (Short/Long)",
              unitPrice: 5,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E005",
              name: "Dress (Short/Long)",
              unitPrice: 5,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E006",
              name: "Coat/Blazer/Jacket",
              unitPrice: 10,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E007",
              name: "Baju Kurung 2pcs (set)",
              unitPrice: 9,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E008",
              name: "Baju Melayu 2pcs (set)",
              unitPrice: 9,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E009",
              name: "Jubah",
              unitPrice: 9,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E010",
              name: "Punjabi Suit 2pcs (set)",
              unitPrice: 9,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E011",
              name: "Saree",
              unitPrice: 10,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E012",
              name: "Undergarment",
              unitPrice: 3,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "E013",
              name: "Tudung/Scarf/Necktie",
              unitPrice: 3,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
          ]
        },
  
        {
          key: "6", name: "Washing Ironing Bedding",
          entries: [
            {
              code: "F001",
              name: "Bedding",
              unitPrice: 10,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "F002",
              name: "Duvet (S)",
              unitPrice: 12,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "F003",
              name: "Duvet (M)",
              unitPrice: 14,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "F004",
              name: "Duvet (K)",
              unitPrice: 16,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "F005",
              name: "Pillowcase / Bolstercase",
              unitPrice: 4,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "F006",
              name: "Curtain",
              unitPrice: 12,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "F007",
              name: "Curtain",
              unitPrice: 6,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "F008",
              name: "Curtain Sheer",
              unitPrice: 15,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "F009",
              name: "Sofa Cover",
              unitPrice: 25,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "F010",
              name: "Cushion Cover",
              unitPrice: 6,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
          ]
        },
  
        {
          key: "7", name: "Handwashing Ironing (Clothes)",
          entries: [
            {
              code: "G001",
              name: "Shirt/T-Shirt/Polo-T/Blouse",
              unitPrice: 6,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G002",
              name: "Trousers/Jeans/Shorts/Joggerpants",
              unitPrice: 6,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G003",
              name: "Vest/Sweater",
              unitPrice: 12,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G004",
              name: "Skirt (Short/Long)",
              unitPrice: 12,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G005",
              name: "Dress (Short/Long)",
              unitPrice: 12,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G006",
              name: "Coat/Blazer/Jacket",
              unitPrice: 12,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G007",
              name: "Baju Kurung 2pcs (set)",
              unitPrice: 10,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G008",
              name: "Baju Melayu 2pcs (set)",
              unitPrice: 10,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G009",
              name: "Jubah",
              unitPrice: 10,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G010",
              name: "Punjabi Suit 2pcs (set)",
              unitPrice: 10,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G011",
              name: "Saree",
              unitPrice: 8,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G012",
              name: "Undergarment",
              unitPrice: 4,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "G013",
              name: "Tudung/Scarf/Necktie",
              unitPrice: 4,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
          ]
        },
        {
          key: "8",  name: "Dry Clean (Clothes)",
          entries: [
            {
              code: "H001",
              name: "Top",
              unitPrice: 8,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H002",
              name: "Bottom",
              unitPrice: 8,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H003",
              name: "Dress",
              unitPrice: 16,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H004",
              name: "Vest/Sweater",
              unitPrice: 13,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H005",
              name: "Coat/Blazer",
              unitPrice: 17,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H006",
              name: "Overcoat",
              unitPrice: 25,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H007",
              name: "Winter Coat",
              unitPrice: 25,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H008",
              name: "Suit 2pcs (set)",
              unitPrice: 23,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H009",
              name: "Baju Kurung 2pcs (set)",
              unitPrice: 16,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H010",
              name: "Baju Melayu 2pcs (set)",
              unitPrice: 16,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H011",
              name: "Jubah",
              unitPrice: 18,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H012",
              name: "Saree",
              unitPrice: 23,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H013",
              name: "Undergarment",
              unitPrice: 6,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H014",
              name: "Tudung/Scarf/Necktie",
              unitPrice: 6,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H015",
              name: "Evening Dress",
              unitPrice: 35,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "H016",
              name: "Wedding Gown",
              unitPrice: 65,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
          ]
        },
  
        {
          key: "9",  name: "Dry Clean Bedding",
          entries: [
            {
              code: "J001",
              name: "Bedsheet/Duvet Cover",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J002",
              name: "Comforter (S)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J003",
              name: "Comforter (Q)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J004",
              name: "Comforter (K)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J005",
              name: "Duvet (S)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J006",
              name: "Duvet (Q)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J007",
              name: "Duvet (K)",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J008",
              name: "Pillowcase/Bolstercase",
              unitPrice: 6,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J009",
              name: "Curtain Sheer",
              unitPrice: 20,
              unitType: "pc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J010",
              name: "Curtain Sheer",
              unitPrice: 15,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J011",
              name: "Cushion Cover",
              unitPrice: 18,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J012",
              name: "Sofa Cover",
              unitPrice: 18,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J013",
              name: "Tablecloth",
              unitPrice: 18,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J014",
              name: "Pillow",
              unitPrice: 25,
              unitType: "kg",
              procTimeReg: 24,
              procTimeExp: 6,
            },
            {
              code: "J015",
              name: "Carpet",
              unitPrice: "-",
              unitType: "spc",
              procTimeReg: 24,
              procTimeExp: 6,
            },
          ]
        },
  
      ]
    }

    return priceList
  }
  